# Generated by Django 5.2 on 2025-04-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InicioCategoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecat', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'inicio_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioComuna',
            fields=[
                ('idcomuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecom', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'inicio_comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioDetalle',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inicio_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioDireccion',
            fields=[
                ('iddireccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripciondir', models.TextField(blank=True, null=True)),
                ('usuario_id', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'inicio_direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioMarca',
            fields=[
                ('idmarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombremarca', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'inicio_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioModelo',
            fields=[
                ('idmodelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombremodelo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'inicio_modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioProducto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=50, null=True)),
                ('precioproducto', models.IntegerField(blank=True, null=True)),
                ('especificacionprod', models.CharField(blank=True, max_length=900, null=True)),
                ('stockprod', models.IntegerField(blank=True, null=True)),
                ('imagenprod', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inicio_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioRegion',
            fields=[
                ('idregion', models.AutoField(primary_key=True, serialize=False)),
                ('nombrereg', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'inicio_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioTipoprod',
            fields=[
                ('idtiporod', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipoprod', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'inicio_tipoprod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioTipousuario',
            fields=[
                ('idtipousuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'inicio_tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioUsuario',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('contrasennia', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'inicio_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InicioVenta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inicio_venta',
                'managed': False,
            },
        ),
    ]
