# Generated by Django 5.2 on 2025-04-28 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='IDCATEGORIA', null=True, on_delete=django.db.models.deletion.CASCADE, to='Inicio.categoria', verbose_name='Categoría'),
        ),
    ]
