# Generated by Django 4.0.4 on 2022-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='productos', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagenCat',
            field=models.ImageField(upload_to='categoria', verbose_name='Imagen de la categoria'),
        ),
        migrations.AlterField(
            model_name='tipoprod',
            name='imagenCat',
            field=models.ImageField(null=True, upload_to='none', verbose_name='Imagen de la categoria'),
        ),
    ]
