# Generated by Django 4.0.4 on 2022-05-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_producto_imagenprod_alter_categoria_imagencat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagenCat',
        ),
    ]
