# Generated by Django 4.0.4 on 2022-05-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_remove_categoria_imagencat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoprod',
            name='imagenCat',
        ),
        migrations.AddField(
            model_name='tipoprod',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='none', verbose_name='Imagen del producto'),
        ),
    ]
