# Generated by Django 4.0.4 on 2022-05-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_remove_tipoprod_imagencat_tipoprod_imagenprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='nombreCom',
            field=models.CharField(max_length=40, verbose_name='Nombre comuna'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombreReg',
            field=models.CharField(max_length=40, verbose_name='Nombre region'),
        ),
    ]
