# Generated by Django 4.0.4 on 2022-05-20 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_alter_comuna_nombrecom_alter_region_nombrereg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='comuna',
        ),
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inicio.region'),
        ),
        migrations.AddField(
            model_name='region',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inicio.comuna'),
        ),
    ]
